### ISSUE TITLE
V3: Typescript missing type declarations

### ISSUE THREAD

**Issue by Digitum** [panva/jose#103]
When installing newest version (3.0.1) there seems that typescript declarations is missing.
Get error:
`Cannot find module 'jose' or its corresponding type declarations.ts(2307)`

Reproduce;
`npm install jose@3.0.1`
Create typescript file:
`
import { JWK, JWKS } from 'jose';
`
Typescript linter will complain of missing type declarations.

This worked on V 2.0.3.

**Comment by panva** [comment]
> This worked on v2.0.3.

Cool, but it won't on v3.x since it's API is completely different. You can check out [each module's docs](https://github.com/panva/jose/tree/master/docs) for how to require them.

**Comment by Digitum** [comment]
Ah, I see now. My dev environment has been open for a couple of days and the new version was released 19 hours ago, so the docs I use was no longer valid :-/
Ill explore new docs...

**Comment by Digitum** [comment]
Still issues when try to compile typescript:
`import generateKeyPair from 'jose/util/generate_key_pair'`
According to docs:
Error: Cannot find module 'jose/util/generate_key_pair'

**Comment by panva** [comment]
What's your node.js version?

**Comment by Dagrut** [comment]
I have the same problem here, using node v12 and esm@3.2.25.

**Comment by panva** [comment]
> I have the same problem here, using node v12 and esm@3.2.25.

Your problem is not the problem here but rather, using an unmaintained and no longer supported ESM loader. ESM is now supported in Node.js LTS/12, LTS/14 and beyond so use it natively instead of the `esm` package.
